
export const cartProduct=[
        {
          name:"Fish",
          poster:"/fish.jpeg",
          rating:"⭐⭐⭐⭐",
          price:"$25.00"
        },
        {
          name:"Mutton",
          poster:"/mutton.jpeg",
          rating:"⭐⭐⭐⭐⭐",
          price:"$40"
        },
        {
          name:"Chicken",
          poster:"/chicken.jpeg",
          rating:"⭐⭐⭐⭐",
          price:"$60"
        },
        {
          name:"Cake",
          poster:"/cake.jpeg",
          rating:"⭐⭐⭐⭐⭐",
          price:"$80"
        },
        {
          name:"Milk",
          poster:"/milk.jpeg",
          rating:"⭐⭐⭐⭐",
          price:"$50"
        },
        {
          name:"Ice",
          poster:"/ice.jpeg",
          rating:"⭐⭐⭐⭐⭐",
          price:"$30"
        },
        {
          name:"Coffee",
          poster:"/coffie.jpeg",
          rating:"⭐⭐⭐⭐",
          price:"$20"
        },
        {
          name:"Rice",
          poster:"/rice.jpeg",
          rating:"⭐⭐⭐",
          price:"$90"
        }
];